export const apiConstants = {
  INDEX: 'API_INDEX',
  INDEX_SUCCESS: 'API_INDEX_SUCCESS',
  INDEX_FAIL: 'API_INDEX_FAIL',

  POST: 'API_POST',
  POST_SUCCESS: 'API_POST_SUCCESS',
  POST_FAIL: 'API_POST_FAIL',

  GET: 'API_GET',
  GET_SUCCESS: 'API_GET_SUCCESS',
  GET_FAIL: 'API_GET_FAIL'
}