export const applicationConstants = {
  GET: 'APP_GET',
  GET_SUCCESS: 'APP_GET_SUCCESS',
  GET_FAIL: 'APP_GET_FAIL',

  POST_STAGE: 'APP_STAGE_POST',
  POST_STAGE_SUCCESS: 'APP_STAGE_POST_SUCCESS',
  POST_STAGE_FAIL: 'APP_STAGE_POST_FAIL'
}