export const metaConstants = {
  POST: 'META_POST',
  POST_SUCCESS: 'META_POST_SUCCESS',
  POST_FAIL: 'META_POST_FAIL',

  GET: 'META_GET',
  GET_SUCCESS: 'META_GET_SUCCESS',
  GET_FAIL: 'META_GET_FAIL',
  
  UPLOAD_FILE: 'UPLOAD_FILE',
  UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
  UPLOAD_FILE_FAIL: 'UPLOAD_FILE_FAIL',

  ADD_OPERATION: 'ADD_OPERATION'
}