export const userConstants = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',

  REGIST: 'REGIST',
  REGIST_SUCCESS: 'REGIST_SUCCESS',
  REGIST_FAIL: 'REGIST_FAIL',

  INDEX: 'INDEX',
  INDEX_SUCCESS: 'INDEX_SUCCESS',
  INDEX_FAIL: 'INDEX_FAIL',

  REGIST_BY_ADMIN: 'REGIST_BY_ADMIN',
  REGIST_BY_ADMIN_SUCCESS: 'REGIST_BY_ADMIN_SUCCESS',
  REGIST_BY_ADMIN_FAIL: 'REGIST_BY_ADMIN_FAIL',

  UNREGIST_BY_ADMIN: 'UNREGIST_BY_ADMIN',
  UNREGIST_BY_ADMIN_SUCCESS: 'UNREGIST_BY_ADMIN_SUCCESS',
  UNREGIST_BY_ADMIN_FAIL: 'UNREGIST_BY_ADMIN_FAIL'
}