export const userConstants = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',

  REGITST: 'REGITST',
  REGITST_SUCCESS: 'REGITST_SUCCESS',
  REGITST_FAIL: 'REGITST_FAIL'
}